name: Verify Human Identity

on:
  workflow_dispatch:
    inputs:
      agent_name:
        description: 'finder'
        required: true
        default: 'arsant'
      agent_description:
        description: 'finder'
        required: true
        default: 'arsant AI Agent'

jobs:
  verify:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Clone verified-agent-identity repo
        run: git clone https://github.com/BillionsNetwork/verified-agent-identity.git temp

      - name: Move scripts
        run: mv temp/scripts ./scripts

      - name: Install dependencies
        run: |
          cd scripts
          npm install

      - name: Create Ethereum Identity
        run: node scripts/createNewEthereumIdentity.js

      - name: Link Human to Agent
        run: |
          node scripts/manualLinkHumanToAgent.js --challenge '{"name": "arsant", "description": "arsant AI Agent"}'
